// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/samantonio28/subscriber-inf/internal/domain (interfaces: PaymentRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "github.com/samantonio28/subscriber-inf/internal/domain"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// GetUserPayments mocks base method.
func (m *MockPaymentRepository) GetUserPayments(arg0 context.Context, arg1 uuid.UUID) ([]domain.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPayments", arg0, arg1)
	ret0, _ := ret[0].([]domain.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPayments indicates an expected call of GetUserPayments.
func (mr *MockPaymentRepositoryMockRecorder) GetUserPayments(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPayments", reflect.TypeOf((*MockPaymentRepository)(nil).GetUserPayments), arg0, arg1)
}

// StorePayment mocks base method.
func (m *MockPaymentRepository) StorePayment(arg0 context.Context, arg1 domain.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePayment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePayment indicates an expected call of StorePayment.
func (mr *MockPaymentRepositoryMockRecorder) StorePayment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePayment", reflect.TypeOf((*MockPaymentRepository)(nil).StorePayment), arg0, arg1)
}
