// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/samantonio28/subscriber-inf/internal/domain (interfaces: PromocodeRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/samantonio28/subscriber-inf/internal/domain"
)

// MockPromocodeRepository is a mock of PromocodeRepository interface.
type MockPromocodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPromocodeRepositoryMockRecorder
}

// MockPromocodeRepositoryMockRecorder is the mock recorder for MockPromocodeRepository.
type MockPromocodeRepositoryMockRecorder struct {
	mock *MockPromocodeRepository
}

// NewMockPromocodeRepository creates a new mock instance.
func NewMockPromocodeRepository(ctrl *gomock.Controller) *MockPromocodeRepository {
	mock := &MockPromocodeRepository{ctrl: ctrl}
	mock.recorder = &MockPromocodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromocodeRepository) EXPECT() *MockPromocodeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPromocodeRepository) Create(arg0 context.Context, arg1 domain.Promocode) (domain.PromocodeID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(domain.PromocodeID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPromocodeRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPromocodeRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockPromocodeRepository) Delete(arg0 context.Context, arg1 domain.PromocodeID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPromocodeRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPromocodeRepository)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockPromocodeRepository) GetAll(arg0 context.Context) ([]domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPromocodeRepositoryMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPromocodeRepository)(nil).GetAll), arg0)
}

// GetByCode mocks base method.
func (m *MockPromocodeRepository) GetByCode(arg0 context.Context, arg1 string) (domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", arg0, arg1)
	ret0, _ := ret[0].(domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockPromocodeRepositoryMockRecorder) GetByCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockPromocodeRepository)(nil).GetByCode), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockPromocodeRepository) GetByID(arg0 context.Context, arg1 domain.PromocodeID) (domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPromocodeRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPromocodeRepository)(nil).GetByID), arg0, arg1)
}

// GetByService mocks base method.
func (m *MockPromocodeRepository) GetByService(arg0 context.Context, arg1 int) ([]domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByService", arg0, arg1)
	ret0, _ := ret[0].([]domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByService indicates an expected call of GetByService.
func (mr *MockPromocodeRepositoryMockRecorder) GetByService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByService", reflect.TypeOf((*MockPromocodeRepository)(nil).GetByService), arg0, arg1)
}

// IncrementUses mocks base method.
func (m *MockPromocodeRepository) IncrementUses(arg0 context.Context, arg1 domain.PromocodeID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUses", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUses indicates an expected call of IncrementUses.
func (mr *MockPromocodeRepositoryMockRecorder) IncrementUses(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUses", reflect.TypeOf((*MockPromocodeRepository)(nil).IncrementUses), arg0, arg1)
}

// Update mocks base method.
func (m *MockPromocodeRepository) Update(arg0 context.Context, arg1 domain.Promocode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPromocodeRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPromocodeRepository)(nil).Update), arg0, arg1)
}
