// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/samantonio28/subscriber-inf/internal/domain (interfaces: PromocodeCache)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/samantonio28/subscriber-inf/internal/domain"
)

// MockPromocodeCache is a mock of PromocodeCache interface.
type MockPromocodeCache struct {
	ctrl     *gomock.Controller
	recorder *MockPromocodeCacheMockRecorder
}

// MockPromocodeCacheMockRecorder is the mock recorder for MockPromocodeCache.
type MockPromocodeCacheMockRecorder struct {
	mock *MockPromocodeCache
}

// NewMockPromocodeCache creates a new mock instance.
func NewMockPromocodeCache(ctrl *gomock.Controller) *MockPromocodeCache {
	mock := &MockPromocodeCache{ctrl: ctrl}
	mock.recorder = &MockPromocodeCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromocodeCache) EXPECT() *MockPromocodeCacheMockRecorder {
	return m.recorder
}

// DeletePromocode mocks base method.
func (m *MockPromocodeCache) DeletePromocode(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePromocode", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePromocode indicates an expected call of DeletePromocode.
func (mr *MockPromocodeCacheMockRecorder) DeletePromocode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePromocode", reflect.TypeOf((*MockPromocodeCache)(nil).DeletePromocode), arg0, arg1)
}

// GetPromocode mocks base method.
func (m *MockPromocodeCache) GetPromocode(arg0 context.Context, arg1 string) (domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromocode", arg0, arg1)
	ret0, _ := ret[0].(domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromocode indicates an expected call of GetPromocode.
func (mr *MockPromocodeCacheMockRecorder) GetPromocode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromocode", reflect.TypeOf((*MockPromocodeCache)(nil).GetPromocode), arg0, arg1)
}

// SetPromocode mocks base method.
func (m *MockPromocodeCache) SetPromocode(arg0 context.Context, arg1 string, arg2 domain.Promocode, arg3 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPromocode", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPromocode indicates an expected call of SetPromocode.
func (mr *MockPromocodeCacheMockRecorder) SetPromocode(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPromocode", reflect.TypeOf((*MockPromocodeCache)(nil).SetPromocode), arg0, arg1, arg2, arg3)
}
