// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/samantonio28/subscriber-inf/internal/domain (interfaces: PromocodeCache)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/promocode_cache.go -package=mocks . PromocodeCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/samantonio28/subscriber-inf/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPromocodeCache is a mock of PromocodeCache interface.
type MockPromocodeCache struct {
	ctrl     *gomock.Controller
	recorder *MockPromocodeCacheMockRecorder
	isgomock struct{}
}

// MockPromocodeCacheMockRecorder is the mock recorder for MockPromocodeCache.
type MockPromocodeCacheMockRecorder struct {
	mock *MockPromocodeCache
}

// NewMockPromocodeCache creates a new mock instance.
func NewMockPromocodeCache(ctrl *gomock.Controller) *MockPromocodeCache {
	mock := &MockPromocodeCache{ctrl: ctrl}
	mock.recorder = &MockPromocodeCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromocodeCache) EXPECT() *MockPromocodeCacheMockRecorder {
	return m.recorder
}

// DeletePromocode mocks base method.
func (m *MockPromocodeCache) DeletePromocode(ctx context.Context, promoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePromocode", ctx, promoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePromocode indicates an expected call of DeletePromocode.
func (mr *MockPromocodeCacheMockRecorder) DeletePromocode(ctx, promoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePromocode", reflect.TypeOf((*MockPromocodeCache)(nil).DeletePromocode), ctx, promoID)
}

// GetPromocode mocks base method.
func (m *MockPromocodeCache) GetPromocode(ctx context.Context, promoID string) (domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromocode", ctx, promoID)
	ret0, _ := ret[0].(domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromocode indicates an expected call of GetPromocode.
func (mr *MockPromocodeCacheMockRecorder) GetPromocode(ctx, promoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromocode", reflect.TypeOf((*MockPromocodeCache)(nil).GetPromocode), ctx, promoID)
}

// SetPromocode mocks base method.
func (m *MockPromocodeCache) SetPromocode(ctx context.Context, promoID string, promo domain.Promocode, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPromocode", ctx, promoID, promo, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPromocode indicates an expected call of SetPromocode.
func (mr *MockPromocodeCacheMockRecorder) SetPromocode(ctx, promoID, promo, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPromocode", reflect.TypeOf((*MockPromocodeCache)(nil).SetPromocode), ctx, promoID, promo, ttl)
}
