// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/promocode_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/samantonio28/subscriber-inf/internal/domain"
)

// MockPromocodeRepository is a mock of PromocodeRepository interface.
type MockPromocodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPromocodeRepositoryMockRecorder
}

// MockPromocodeRepositoryMockRecorder is the mock recorder for MockPromocodeRepository.
type MockPromocodeRepositoryMockRecorder struct {
	mock *MockPromocodeRepository
}

// NewMockPromocodeRepository creates a new mock instance.
func NewMockPromocodeRepository(ctrl *gomock.Controller) *MockPromocodeRepository {
	mock := &MockPromocodeRepository{ctrl: ctrl}
	mock.recorder = &MockPromocodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromocodeRepository) EXPECT() *MockPromocodeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPromocodeRepository) Create(ctx context.Context, pc domain.Promocode) (domain.PromocodeID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pc)
	ret0, _ := ret[0].(domain.PromocodeID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPromocodeRepositoryMockRecorder) Create(ctx, pc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPromocodeRepository)(nil).Create), ctx, pc)
}

// Delete mocks base method.
func (m *MockPromocodeRepository) Delete(ctx context.Context, id domain.PromocodeID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPromocodeRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPromocodeRepository)(nil).Delete), ctx, id)
}

// GetByCode mocks base method.
func (m *MockPromocodeRepository) GetByCode(ctx context.Context, code string) (domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockPromocodeRepositoryMockRecorder) GetByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockPromocodeRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockPromocodeRepository) GetByID(ctx context.Context, id domain.PromocodeID) (domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPromocodeRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPromocodeRepository)(nil).GetByID), ctx, id)
}

// GetByService mocks base method.
func (m *MockPromocodeRepository) GetByService(ctx context.Context, serviceID int) ([]domain.Promocode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByService", ctx, serviceID)
	ret0, _ := ret[0].([]domain.Promocode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByService indicates an expected call of GetByService.
func (mr *MockPromocodeRepositoryMockRecorder) GetByService(ctx, serviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByService", reflect.TypeOf((*MockPromocodeRepository)(nil).GetByService), ctx, serviceID)
}

// IncrementUses mocks base method.
func (m *MockPromocodeRepository) IncrementUses(ctx context.Context, id domain.PromocodeID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUses", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUses indicates an expected call of IncrementUses.
func (mr *MockPromocodeRepositoryMockRecorder) IncrementUses(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUses", reflect.TypeOf((*MockPromocodeRepository)(nil).IncrementUses), ctx, id)
}

// Update mocks base method.
func (m *MockPromocodeRepository) Update(ctx context.Context, pc domain.Promocode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPromocodeRepositoryMockRecorder) Update(ctx, pc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPromocodeRepository)(nil).Update), ctx, pc)
}
