// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/sub_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "github.com/samantonio28/subscriber-inf/internal/domain"
)

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// DeleteSub mocks base method.
func (m *MockSubscriptionRepository) DeleteSub(ctx context.Context, subId domain.SubID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSub", ctx, subId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSub indicates an expected call of DeleteSub.
func (mr *MockSubscriptionRepositoryMockRecorder) DeleteSub(ctx, subId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSub", reflect.TypeOf((*MockSubscriptionRepository)(nil).DeleteSub), ctx, subId)
}

// StoreSub mocks base method.
func (m *MockSubscriptionRepository) StoreSub(ctx context.Context, sub domain.Subscription) (domain.SubID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSub", ctx, sub)
	ret0, _ := ret[0].(domain.SubID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreSub indicates an expected call of StoreSub.
func (mr *MockSubscriptionRepositoryMockRecorder) StoreSub(ctx, sub interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSub", reflect.TypeOf((*MockSubscriptionRepository)(nil).StoreSub), ctx, sub)
}

// Sub mocks base method.
func (m *MockSubscriptionRepository) Sub(ctx context.Context, subId domain.SubID) (domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sub", ctx, subId)
	ret0, _ := ret[0].(domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sub indicates an expected call of Sub.
func (mr *MockSubscriptionRepositoryMockRecorder) Sub(ctx, subId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sub", reflect.TypeOf((*MockSubscriptionRepository)(nil).Sub), ctx, subId)
}

// SubsTotalCosts mocks base method.
func (m *MockSubscriptionRepository) SubsTotalCosts(ctx context.Context, filter domain.SubsFilter) (int, []domain.SubID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubsTotalCosts", ctx, filter)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]domain.SubID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SubsTotalCosts indicates an expected call of SubsTotalCosts.
func (mr *MockSubscriptionRepositoryMockRecorder) SubsTotalCosts(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubsTotalCosts", reflect.TypeOf((*MockSubscriptionRepository)(nil).SubsTotalCosts), ctx, filter)
}

// UpdateSub mocks base method.
func (m *MockSubscriptionRepository) UpdateSub(ctx context.Context, sub domain.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSub", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSub indicates an expected call of UpdateSub.
func (mr *MockSubscriptionRepositoryMockRecorder) UpdateSub(ctx, sub interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSub", reflect.TypeOf((*MockSubscriptionRepository)(nil).UpdateSub), ctx, sub)
}

// UserSubs mocks base method.
func (m *MockSubscriptionRepository) UserSubs(ctx context.Context, userId uuid.UUID) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserSubs", ctx, userId)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserSubs indicates an expected call of UserSubs.
func (mr *MockSubscriptionRepositoryMockRecorder) UserSubs(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserSubs", reflect.TypeOf((*MockSubscriptionRepository)(nil).UserSubs), ctx, userId)
}
