// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/subscription_plan_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/samantonio28/subscriber-inf/internal/domain"
)

// MockSubscriptionPlanRepository is a mock of SubscriptionPlanRepository interface.
type MockSubscriptionPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionPlanRepositoryMockRecorder
}

// MockSubscriptionPlanRepositoryMockRecorder is the mock recorder for MockSubscriptionPlanRepository.
type MockSubscriptionPlanRepositoryMockRecorder struct {
	mock *MockSubscriptionPlanRepository
}

// NewMockSubscriptionPlanRepository creates a new mock instance.
func NewMockSubscriptionPlanRepository(ctrl *gomock.Controller) *MockSubscriptionPlanRepository {
	mock := &MockSubscriptionPlanRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionPlanRepository) EXPECT() *MockSubscriptionPlanRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubscriptionPlanRepository) Create(ctx context.Context, plan domain.SubscriptionPlan) (domain.PlanID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, plan)
	ret0, _ := ret[0].(domain.PlanID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Create(ctx, plan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Create), ctx, plan)
}

// Delete mocks base method.
func (m *MockSubscriptionPlanRepository) Delete(ctx context.Context, id domain.PlanID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockSubscriptionPlanRepository) GetByID(ctx context.Context, id domain.PlanID) (domain.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).GetByID), ctx, id)
}

// GetByService mocks base method.
func (m *MockSubscriptionPlanRepository) GetByService(ctx context.Context, serviceID int) ([]domain.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByService", ctx, serviceID)
	ret0, _ := ret[0].([]domain.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByService indicates an expected call of GetByService.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) GetByService(ctx, serviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByService", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).GetByService), ctx, serviceID)
}

// Update mocks base method.
func (m *MockSubscriptionPlanRepository) Update(ctx context.Context, plan domain.SubscriptionPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Update(ctx, plan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Update), ctx, plan)
}
