// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/samantonio28/subscriber-inf/internal/domain (interfaces: SubscriptionPlanCache)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/samantonio28/subscriber-inf/internal/domain"
)

// MockSubscriptionPlanCache is a mock of SubscriptionPlanCache interface.
type MockSubscriptionPlanCache struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionPlanCacheMockRecorder
}

// MockSubscriptionPlanCacheMockRecorder is the mock recorder for MockSubscriptionPlanCache.
type MockSubscriptionPlanCacheMockRecorder struct {
	mock *MockSubscriptionPlanCache
}

// NewMockSubscriptionPlanCache creates a new mock instance.
func NewMockSubscriptionPlanCache(ctrl *gomock.Controller) *MockSubscriptionPlanCache {
	mock := &MockSubscriptionPlanCache{ctrl: ctrl}
	mock.recorder = &MockSubscriptionPlanCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionPlanCache) EXPECT() *MockSubscriptionPlanCacheMockRecorder {
	return m.recorder
}

// DeleteSubscriptionPlan mocks base method.
func (m *MockSubscriptionPlanCache) DeleteSubscriptionPlan(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionPlan", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptionPlan indicates an expected call of DeleteSubscriptionPlan.
func (mr *MockSubscriptionPlanCacheMockRecorder) DeleteSubscriptionPlan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionPlan", reflect.TypeOf((*MockSubscriptionPlanCache)(nil).DeleteSubscriptionPlan), arg0, arg1)
}

// GetSubscriptionPlan mocks base method.
func (m *MockSubscriptionPlanCache) GetSubscriptionPlan(arg0 context.Context, arg1 string) (domain.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionPlan", arg0, arg1)
	ret0, _ := ret[0].(domain.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionPlan indicates an expected call of GetSubscriptionPlan.
func (mr *MockSubscriptionPlanCacheMockRecorder) GetSubscriptionPlan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionPlan", reflect.TypeOf((*MockSubscriptionPlanCache)(nil).GetSubscriptionPlan), arg0, arg1)
}

// SetSubscriptionPlan mocks base method.
func (m *MockSubscriptionPlanCache) SetSubscriptionPlan(arg0 context.Context, arg1 string, arg2 domain.SubscriptionPlan, arg3 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSubscriptionPlan", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSubscriptionPlan indicates an expected call of SetSubscriptionPlan.
func (mr *MockSubscriptionPlanCacheMockRecorder) SetSubscriptionPlan(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubscriptionPlan", reflect.TypeOf((*MockSubscriptionPlanCache)(nil).SetSubscriptionPlan), arg0, arg1, arg2, arg3)
}
