// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/samantonio28/subscriber-inf/internal/domain (interfaces: SubscriptionPlanRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/samantonio28/subscriber-inf/internal/domain"
)

// MockSubscriptionPlanRepository is a mock of SubscriptionPlanRepository interface.
type MockSubscriptionPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionPlanRepositoryMockRecorder
}

// MockSubscriptionPlanRepositoryMockRecorder is the mock recorder for MockSubscriptionPlanRepository.
type MockSubscriptionPlanRepositoryMockRecorder struct {
	mock *MockSubscriptionPlanRepository
}

// NewMockSubscriptionPlanRepository creates a new mock instance.
func NewMockSubscriptionPlanRepository(ctrl *gomock.Controller) *MockSubscriptionPlanRepository {
	mock := &MockSubscriptionPlanRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionPlanRepository) EXPECT() *MockSubscriptionPlanRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubscriptionPlanRepository) Create(arg0 context.Context, arg1 domain.SubscriptionPlan) (domain.PlanID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(domain.PlanID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockSubscriptionPlanRepository) Delete(arg0 context.Context, arg1 domain.PlanID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockSubscriptionPlanRepository) GetAll(arg0 context.Context) ([]domain.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]domain.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).GetAll), arg0)
}

// GetByID mocks base method.
func (m *MockSubscriptionPlanRepository) GetByID(arg0 context.Context, arg1 domain.PlanID) (domain.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(domain.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).GetByID), arg0, arg1)
}

// GetByService mocks base method.
func (m *MockSubscriptionPlanRepository) GetByService(arg0 context.Context, arg1 int) ([]domain.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByService", arg0, arg1)
	ret0, _ := ret[0].([]domain.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByService indicates an expected call of GetByService.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) GetByService(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByService", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).GetByService), arg0, arg1)
}

// Update mocks base method.
func (m *MockSubscriptionPlanRepository) Update(arg0 context.Context, arg1 domain.SubscriptionPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Update), arg0, arg1)
}
