// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/samantonio28/subscriber-inf/internal/domain (interfaces: SubscriptionPlanCache)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/subscription_plan_cache.go -package=mocks . SubscriptionPlanCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/samantonio28/subscriber-inf/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionPlanCache is a mock of SubscriptionPlanCache interface.
type MockSubscriptionPlanCache struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionPlanCacheMockRecorder
	isgomock struct{}
}

// MockSubscriptionPlanCacheMockRecorder is the mock recorder for MockSubscriptionPlanCache.
type MockSubscriptionPlanCacheMockRecorder struct {
	mock *MockSubscriptionPlanCache
}

// NewMockSubscriptionPlanCache creates a new mock instance.
func NewMockSubscriptionPlanCache(ctrl *gomock.Controller) *MockSubscriptionPlanCache {
	mock := &MockSubscriptionPlanCache{ctrl: ctrl}
	mock.recorder = &MockSubscriptionPlanCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionPlanCache) EXPECT() *MockSubscriptionPlanCacheMockRecorder {
	return m.recorder
}

// DeleteSubscriptionPlan mocks base method.
func (m *MockSubscriptionPlanCache) DeleteSubscriptionPlan(ctx context.Context, planID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionPlan", ctx, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptionPlan indicates an expected call of DeleteSubscriptionPlan.
func (mr *MockSubscriptionPlanCacheMockRecorder) DeleteSubscriptionPlan(ctx, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionPlan", reflect.TypeOf((*MockSubscriptionPlanCache)(nil).DeleteSubscriptionPlan), ctx, planID)
}

// GetSubscriptionPlan mocks base method.
func (m *MockSubscriptionPlanCache) GetSubscriptionPlan(ctx context.Context, planID string) (domain.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionPlan", ctx, planID)
	ret0, _ := ret[0].(domain.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionPlan indicates an expected call of GetSubscriptionPlan.
func (mr *MockSubscriptionPlanCacheMockRecorder) GetSubscriptionPlan(ctx, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionPlan", reflect.TypeOf((*MockSubscriptionPlanCache)(nil).GetSubscriptionPlan), ctx, planID)
}

// SetSubscriptionPlan mocks base method.
func (m *MockSubscriptionPlanCache) SetSubscriptionPlan(ctx context.Context, planID string, plan domain.SubscriptionPlan, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSubscriptionPlan", ctx, planID, plan, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSubscriptionPlan indicates an expected call of SetSubscriptionPlan.
func (mr *MockSubscriptionPlanCacheMockRecorder) SetSubscriptionPlan(ctx, planID, plan, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubscriptionPlan", reflect.TypeOf((*MockSubscriptionPlanCache)(nil).SetSubscriptionPlan), ctx, planID, plan, ttl)
}
