// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/samantonio28/subscriber-inf/internal/domain (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/user_repository.go -package=mocks . UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/samantonio28/subscriber-inf/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUserRepository) GetUser(ctx context.Context, userID uuid.UUID) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserRepositoryMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserRepository)(nil).GetUser), ctx, userID)
}

// GetUserByReferralCode mocks base method.
func (m *MockUserRepository) GetUserByReferralCode(ctx context.Context, referralCode string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByReferralCode", ctx, referralCode)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByReferralCode indicates an expected call of GetUserByReferralCode.
func (mr *MockUserRepositoryMockRecorder) GetUserByReferralCode(ctx, referralCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByReferralCode", reflect.TypeOf((*MockUserRepository)(nil).GetUserByReferralCode), ctx, referralCode)
}

// SetAppCurrentUserID mocks base method.
func (m *MockUserRepository) SetAppCurrentUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAppCurrentUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAppCurrentUserID indicates an expected call of SetAppCurrentUserID.
func (mr *MockUserRepositoryMockRecorder) SetAppCurrentUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppCurrentUserID", reflect.TypeOf((*MockUserRepository)(nil).SetAppCurrentUserID), ctx, userID)
}

// StoreReferral mocks base method.
func (m *MockUserRepository) StoreReferral(ctx context.Context, referrerID, referredID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreReferral", ctx, referrerID, referredID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreReferral indicates an expected call of StoreReferral.
func (mr *MockUserRepositoryMockRecorder) StoreReferral(ctx, referrerID, referredID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreReferral", reflect.TypeOf((*MockUserRepository)(nil).StoreReferral), ctx, referrerID, referredID)
}

// StoreUser mocks base method.
func (m *MockUserRepository) StoreUser(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreUser indicates an expected call of StoreUser.
func (mr *MockUserRepositoryMockRecorder) StoreUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUser", reflect.TypeOf((*MockUserRepository)(nil).StoreUser), ctx, user)
}

// UpdateUser mocks base method.
func (m *MockUserRepository) UpdateUser(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepositoryMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), ctx, user)
}
