BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE subscription_type AS ENUM ('usual', 'promocode');
CREATE TYPE payment_type AS ENUM ('income', 'expence');

CREATE TABLE services (
    service_id INTEGER GENERATED ALWAYS AS IDENTITY,
    service_name VARCHAR,
    sub_duration_id_default INTEGER,
    users_count INTEGER,
    has_promocodes BOOLEAN
);

CREATE TABLE subscriptions (
    sub_id INTEGER GENERATED ALWAYS AS IDENTITY,
    user_id UUID,
    service_id INTEGER,
    price INTEGER,
    sub_type subscription_type,
    start_date DATE,
    end_date DATE
);

CREATE TABLE users (
    user_id UUID,
    email VARCHAR,
    password VARCHAR(30),
    user_name VARCHAR(20),
    age INTEGER,
    balance INTEGER
);

-- CREATE TABLE users_subs (
--     sub_id INTEGER,
--     user_id UUID
-- );

CREATE TABLE sub_durations (
    sub_duration_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    service_id INTEGER,
    duration_days INTEGER
);

CREATE TABLE promocodes (
    promocode_id INTEGER,
    service_id INTEGER,
    promocode VARCHAR(10),
    sub_duration_days INTEGER,
    sub_id INTEGER,
    expires_at DATE
);

CREATE TABLE cards (
    user_id UUID,
    card_number VARCHAR(30)
);

CREATE TABLE payments (
    paym_id INTEGER GENERATED ALWAYS AS IDENTITY,
    user_id UUID,
    card_number VARCHAR(30),
    amount INTEGER,
    paym_type payment_type
);

COMMIT;
