apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: dev
    user: postgres
    secureJsonData:
      password: "secret"
    jsonData:
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
