postgres:
  host: "localhost"
  port: 8000
  user: "postgres"
  password: "secret"
  dbname: "dev"
  sslmode: "disable"
  pool:
    max_conns: 10
    min_conns: 2
    max_conn_lifetime: "1h"
    max_conn_idle_time: "5m"
