package usecase

import (
	"context"

	"github.com/samantonio28/subscriber-inf/internal/domain"
	"github.com/samantonio28/subscriber-inf/internal/logger"
)

type CreateSubscriptionPlanUC struct {
	planRepo domain.SubscriptionPlanRepository
	logger   *logger.LogrusLogger
}

func NewCreateSubscriptionPlanUC(planRepo domain.SubscriptionPlanRepository, logger *logger.LogrusLogger) (*CreateSubscriptionPlanUC, error) {
	if planRepo == nil {
		return nil, domain.ErrInvalidSubRepo
	}
	if logger == nil {
		return nil, domain.ErrInvalidLogger
	}
	return &CreateSubscriptionPlanUC{planRepo: planRepo, logger: logger}, nil
}

type CreateSubscriptionPlanInput struct {
	ServiceID    int
	Name         string
	DurationDays int
	Price        int
}

func (uc *CreateSubscriptionPlanUC) Create(ctx context.Context, input CreateSubscriptionPlanInput) (domain.PlanID, error) {
	plan, err := domain.NewSubscriptionPlan(
		0, // ID will be generated by DB
		input.ServiceID,
		input.Name,
		input.DurationDays,
		input.Price,
	)
	if err != nil {
		return 0, err
	}

	id, err := uc.planRepo.Create(ctx, *plan)
	if err != nil {
		uc.logger.WithFields(map[string]any{"error": err})
		return 0, err
	}
	uc.logger.Info("subscription plan created")
	return id, nil
}