package usecase

import (
	"context"

	"github.com/samantonio28/subscriber-inf/internal/domain"
	"github.com/samantonio28/subscriber-inf/internal/logger"
)

type CreateSubscriptionPlanUC struct {
	planRepo domain.SubscriptionPlanRepository
	logger   logger.Logger
}

func NewCreateSubscriptionPlanUC(planRepo domain.SubscriptionPlanRepository, logger logger.Logger) (*CreateSubscriptionPlanUC, error) {
	if planRepo == nil {
		return nil, domain.ErrInvalidSubRepo
	}
	if logger == nil {
		return nil, domain.ErrInvalidLogger
	}
	return &CreateSubscriptionPlanUC{planRepo: planRepo, logger: logger}, nil
}

type CreateSubscriptionPlanInput struct {
	ServiceID    int
	Name         string
	DurationDays int
	Price        int
}

func (uc *CreateSubscriptionPlanUC) Create(ctx context.Context, input CreateSubscriptionPlanInput) (domain.PlanID, error) {
	uc.logger.Debug("creating new subscription plan", "service_id", input.ServiceID, "name", input.Name, "duration_days", input.DurationDays, "price", input.Price)
	plan, err := domain.NewSubscriptionPlan(
		0, // ID will be generated by DB
		input.ServiceID,
		input.Name,
		input.DurationDays,
		input.Price,
	)
	if err != nil {
		uc.logger.Error("failed to create subscription plan domain object", "error", err, "input", input)
		return 0, err
	}

	id, err := uc.planRepo.Create(ctx, *plan)
	if err != nil {
		uc.logger.Error("failed to store subscription plan in database", "error", err, "plan", plan, "source", "database")
		return 0, err
	}
	uc.logger.Info("subscription plan created successfully", "plan_id", id, "service_id", input.ServiceID, "source", "database")
	// Note: cache invalidation may be needed if caching is implemented for this plan
	uc.logger.Debug("cache invalidation not performed (no cache dependency)")
	return id, nil
}