package usecase

import (
	"context"
	"time"

	"github.com/samantonio28/subscriber-inf/internal/domain"
	"github.com/samantonio28/subscriber-inf/internal/logger"
)

type CreatePromocodeUC struct {
	promocodeRepo domain.PromocodeRepository
	logger        *logger.LogrusLogger
}

func NewCreatePromocodeUC(promocodeRepo domain.PromocodeRepository, logger *logger.LogrusLogger) (*CreatePromocodeUC, error) {
	if promocodeRepo == nil {
		return nil, domain.ErrInvalidSubRepo
	}
	if logger == nil {
		return nil, domain.ErrInvalidLogger
	}
	return &CreatePromocodeUC{promocodeRepo: promocodeRepo, logger: logger}, nil
}

type CreatePromocodeInput struct {
	ServiceID    int
	Value        string
	PlanID       *int
	SubID        *int
	ExpiresAt    time.Time
	Discount     int
	MaxUses      int
	DurationDays int
}

func (uc *CreatePromocodeUC) Create(ctx context.Context, input CreatePromocodeInput) (domain.PromocodeID, error) {
	// Validate discount
	if input.Discount < 0 || input.Discount > 100 {
		return 0, domain.ErrInvalidInput
	}
	if input.MaxUses < 1 {
		input.MaxUses = 1
	}
	if input.DurationDays <= 0 {
		input.DurationDays = 3
	}
	// Ensure expires_at is set
	expiresAt := input.ExpiresAt
	if expiresAt.IsZero() {
		expiresAt = time.Now().AddDate(0, 0, input.DurationDays)
	}

	promocode, err := domain.NewPromocode(
		0, // ID will be generated by DB
		input.ServiceID,
		input.Value,
		input.PlanID,
		input.SubID,
		expiresAt,
		time.Now(),
		input.Discount,
		input.MaxUses,
		0, // cur_uses
		domain.PromocodeStatusActive,
		input.DurationDays,
	)
	if err != nil {
		return 0, err
	}

	id, err := uc.promocodeRepo.Create(ctx, *promocode)
	if err != nil {
		uc.logger.WithFields(map[string]any{"error": err})
		return 0, err
	}
	uc.logger.Info("promocode created")
	return id, nil
}
